### ISSUE TITLE
Don't treat style rules as errors but warnings

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/code-style#12]
Currently there are many style rules in both Solidity and JavaScript linters which are treated as errors.

In the interested of reducing friction for contributors, but without giving up on our pursuit of code style consistency, we have decided to demote style rules to warnings. This will allow us to ask contributors nicely to adhere to our style, instead of them running against a failed CI build.

**Comment by frangio** [comment]
We may need to review OpenZeppelin's configuration.

**Comment by elopio** [comment]
Here's for solidity: #15 
I feel like I've lost a piece of my soul here :scream: :scream: :scream:
